import "@/styles/globals.css";
import "swiper/css"
import { Inter } from "next/font/google";
import BottomNav from '@/components/BottomNav';
import clsx from 'clsx';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx([inter.className, 'h-screen overflow-hidden'])}>
        <main className="h-screen">{children}</main>
        <BottomNav/>
      </body>
    </html>
  );
}
